"""add email to files

Revision ID: 66e4d3b4673e
Revises: 105610687c49
Create Date: 2026-09-09 12:33:54.487627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e4d3b4673e'
down_revision: Union[str, Sequence[str], None] = '105610687c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('email', sa.String(length=320), nullable=False, server_default=''))
    op.alter_column('files', 'email', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'email')
    # ### end Alembic commands ###
